name       : amfora
version    : 1.9.1
release    : 3
source     :
    - https://github.com/makeworld-the-better-one/amfora/archive/refs/tags/v1.9.1.tar.gz : f10811cee8a4e45cac13a1f6ff883b576e2daca2871ac6844ad5046b17269c16
license    : GPL-3.0-or-later
component  : network.clients
summary    : Gemini client for the terminal
description: |
    Amfora is a terminal-based, cross-platform Gemini protocol client
networking : yes
environment: |
    export VERSION=$version
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 amfora $installdir/usr/bin/amfora
    install -Dm00644 amfora.desktop $installdir/usr/share/applications/amfora.desktop
